language: java

jdk:
  - openjdk8

# Codecov.io test coverage report
# see https://github.com/codecov/example-java
before_script:
  - pip install --user codecov
after_success:
  - gradle jacocoTestReport
  - codecov
